window.esdocSearchIndex = [
  [
    "ai-boilerplate/node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html",
    "<span>SlidingBlockPuzzle</span> <span class=\"search-result-import-path\">ai-boilerplate/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js</span>",
    "class"
  ],
  [
    "ai-boilerplate/node-ai-boilerplate-nahid/src/common/queue.js~fifoqueue",
    "variable/index.html#static-variable-fifoQueue",
    "<span>fifoQueue</span> <span class=\"search-result-import-path\">ai-boilerplate/node-ai-boilerplate-nahid/src/common/queue.js</span>",
    "variable"
  ],
  [
    "ai-boilerplate/node-ai-boilerplate-nahid/src/search/graphsearch.js~graphsearch",
    "function/index.html#static-function-graphSearch",
    "<span>graphSearch</span> <span class=\"search-result-import-path\">ai-boilerplate/node-ai-boilerplate-nahid/src/search/graphSearch.js</span>",
    "function"
  ],
  [
    "ai-boilerplate/node-ai-boilerplate-nahid/src/common/queue.js~lifoqueue",
    "variable/index.html#static-variable-lifoQueue",
    "<span>lifoQueue</span> <span class=\"search-result-import-path\">ai-boilerplate/node-ai-boilerplate-nahid/src/common/queue.js</span>",
    "variable"
  ],
  [
    "ai-boilerplate/node-ai-boilerplate-nahid/src/common/queue.js~priorityqueue",
    "function/index.html#static-function-priorityQueue",
    "<span>priorityQueue</span> <span class=\"search-result-import-path\">ai-boilerplate/node-ai-boilerplate-nahid/src/common/queue.js</span>",
    "function"
  ],
  [
    "ai-boilerplate/node-ai-boilerplate-nahid/src/common/sequence.js~sequencefirst",
    "function/index.html#static-function-sequenceFirst",
    "<span>sequenceFirst</span> <span class=\"search-result-import-path\">ai-boilerplate/node-ai-boilerplate-nahid/src/common/sequence.js</span>",
    "function"
  ],
  [
    "ai-boilerplate/node-ai-boilerplate-nahid/src/common/sequence.js~sequenceisempty",
    "function/index.html#static-function-sequenceIsEmpty",
    "<span>sequenceIsEmpty</span> <span class=\"search-result-import-path\">ai-boilerplate/node-ai-boilerplate-nahid/src/common/sequence.js</span>",
    "function"
  ],
  [
    "ai-boilerplate/node-ai-boilerplate-nahid/src/common/sequence.js~sequencerest",
    "function/index.html#static-function-sequenceRest",
    "<span>sequenceRest</span> <span class=\"search-result-import-path\">ai-boilerplate/node-ai-boilerplate-nahid/src/common/sequence.js</span>",
    "function"
  ],
  [
    "ai-boilerplate/node-ai-boilerplate-nahid/src/agents/simpleproblemsolvingagent.js~simpleproblemsolvingagent",
    "function/index.html#static-function-simpleProblemSolvingAgent",
    "<span>simpleProblemSolvingAgent</span> <span class=\"search-result-import-path\">ai-boilerplate/node-ai-boilerplate-nahid/src/agents/simpleProblemSolvingAgent.js</span>",
    "function"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~String",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~function",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~null",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~number",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~object",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~string",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "node-ai-boilerplate-nahid/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "node-ai-boilerplate-nahid/src/agents/index.js",
    "file/node-ai-boilerplate-nahid/src/agents/index.js.html",
    "node-ai-boilerplate-nahid/src/agents/index.js",
    "file"
  ],
  [
    "node-ai-boilerplate-nahid/src/agents/simpleproblemsolvingagent.js",
    "file/node-ai-boilerplate-nahid/src/agents/simpleProblemSolvingAgent.js.html",
    "node-ai-boilerplate-nahid/src/agents/simpleProblemSolvingAgent.js",
    "file"
  ],
  [
    "node-ai-boilerplate-nahid/src/common/index.js",
    "file/node-ai-boilerplate-nahid/src/common/index.js.html",
    "node-ai-boilerplate-nahid/src/common/index.js",
    "file"
  ],
  [
    "node-ai-boilerplate-nahid/src/common/queue.js",
    "file/node-ai-boilerplate-nahid/src/common/queue.js.html",
    "node-ai-boilerplate-nahid/src/common/queue.js",
    "file"
  ],
  [
    "node-ai-boilerplate-nahid/src/common/queue.js~queue",
    "typedef/index.html#static-typedef-Queue",
    "node-ai-boilerplate-nahid/src/common/queue.js~Queue",
    "typedef"
  ],
  [
    "node-ai-boilerplate-nahid/src/common/sequence.js",
    "file/node-ai-boilerplate-nahid/src/common/sequence.js.html",
    "node-ai-boilerplate-nahid/src/common/sequence.js",
    "file"
  ],
  [
    "node-ai-boilerplate-nahid/src/common/sequence.js~sequence",
    "typedef/index.html#static-typedef-Sequence",
    "node-ai-boilerplate-nahid/src/common/sequence.js~Sequence",
    "typedef"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js",
    "file/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js.html",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js",
    "file"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#constructor",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-constructor-constructor",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#constructor",
    "method"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#creategoalstate",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-method-createGoalState",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#createGoalState",
    "method"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#createrandominitialstate",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-method-createRandomInitialState",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#createRandomInitialState",
    "method"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#getactions",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-method-getActions",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#getActions",
    "method"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#height",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-member-height",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#height",
    "member"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#isgoalstate",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-method-isGoalState",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#isGoalState",
    "method"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#performaction",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-method-performAction",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#performAction",
    "method"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#print",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-method-print",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#print",
    "method"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#stateserialise",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-method-stateSerialise",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#stateSerialise",
    "method"
  ],
  [
    "node-ai-boilerplate-nahid/src/games/slidingblockpuzzle.js~slidingblockpuzzle#width",
    "class/node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle.html#instance-member-width",
    "node-ai-boilerplate-nahid/src/games/SlidingBlockPuzzle.js~SlidingBlockPuzzle#width",
    "member"
  ],
  [
    "node-ai-boilerplate-nahid/src/index.js",
    "file/node-ai-boilerplate-nahid/src/index.js.html",
    "node-ai-boilerplate-nahid/src/index.js",
    "file"
  ],
  [
    "node-ai-boilerplate-nahid/src/search/graphsearch.js",
    "file/node-ai-boilerplate-nahid/src/search/graphSearch.js.html",
    "node-ai-boilerplate-nahid/src/search/graphSearch.js",
    "file"
  ],
  [
    "node-ai-boilerplate-nahid/src/search/treesearch.js",
    "file/node-ai-boilerplate-nahid/src/search/treeSearch.js.html",
    "node-ai-boilerplate-nahid/src/search/treeSearch.js",
    "file"
  ]
]